[package]
name = "livtet-desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["Jacky Alcine <yo@jacky.wtf>"]
edition.workspace = true
rust-version.workspace = true
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "livtet_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-decorum = { git = "https://github.com/olamaelcu/tauri-plugin-decorum" }
tauri-plugin-mcp-bridge = "0.12"
livtet-core = { git = "https://github.com/olamaelcu/livtet", branch = "main" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
camino = { version = "1.2.5", features = ["serde1"] }
tracing = "0.1.44"
tracing-appender = "0.2"
tracing-forest = { version = "0.3.1", features = ["env-filter"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
miette = "7.6.0"
thiserror = "2.0.19"
fs-err = { version = "3.3.1", features = ["debug", "tokio"] }
