[tools]
"aqua:getsops/sops" = "3.13.2"
"aqua:age" = "1.3.1"
"aqua:jqlang/jq" = "1.8.2"
adr-tools = "latest"
taskwarrior = "3.4.2"
"pipx:taskwarrior-mcp" = "0.2.0"

[env]
_.file = ".mise/secrets.env"
RUST_BACKTRACE = "full"
TASKRC = "{{ [config_root, '.taskrc']   | join_path }}"
TASKDATA = "{{ [config_root, '.taskdata'] | join_path }}"
RUST_LOG = "tao=warn,wry=warn,log=warn,trace"

[tasks.dev]
run = ["cargo run --bin generate-bindings", "pnpm tauri dev"]

depends = ["secrets-export-env"]
