import type { SearchHit } from "./types";

// 12 desaturated tones that read as "book cover" colours and stay
// legible under both `wa-light` and `wa-dark` themes. Indexed by the
// hash of a title so the same book always gets the same colour.
const PALETTE = [
  "#4a5759", // slate
  "#6b7e8a", // blue-grey
  "#8b7e6b", // warm grey
  "#7a6b8b", // mauve
  "#6b8b7e", // sage
  "#8b6b7a", // dusty rose
  "#5e6b8b", // steel blue
  "#8b6b5e", // terracotta
  "#6b8b6b", // moss
  "#8b8b6b", // olive
  "#6b6b8b", // indigo
  "#8b5e6b", // burgundy
] as const;

// FNV-1a 32-bit hash. Stable, fast, no crypto.
function hashTitle(title: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < title.length; i++) {
    h ^= title.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

export function dominantColorFor(title: string): string {
  return PALETTE[hashTitle(title) % PALETTE.length];
}

// First letter, uppercased. Used as the cover's monogram.
export function coverLetter(title: string): string {
  const trimmed = title.trim();
  return (trimmed[0] ?? "?").toUpperCase();
}

// Mock data. `kind: "work"` for all rows so the grid shows one card
// per work. The 26-char `work_id` strings are stable placeholders;
// they don't need to be real ULIDs because we never look them up.
//
// Cover enough formats (EPUB, PDF, MOBI, AZW3) and enough languages
// (English, French, German, Japanese, Spanish) that the filter chips
// meaningfully change the visible grid.
export const mockHits: SearchHit[] = [
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA1",
    author_id: null,
    title: "The Pragmatic Programmer",
    work_title: "The Pragmatic Programmer",
    edition_title: null,
    authors: ["Andrew Hunt", "David Thomas"],
    isbn: "9780135957059",
    format: "PDF",
    language: "English",
    published_date: "2019-09-13",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA2",
    author_id: null,
    title: "Designing Data-Intensive Applications",
    work_title: "Designing Data-Intensive Applications",
    edition_title: null,
    authors: ["Martin Kleppmann"],
    isbn: "9781449373320",
    format: "EPUB",
    language: "English",
    published_date: "2017-04-11",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA3",
    author_id: null,
    title: "Crafting Interpreters",
    work_title: "Crafting Interpreters",
    edition_title: null,
    authors: ["Robert Nystrom"],
    isbn: null,
    format: "EPUB",
    language: "English",
    published_date: "2021-07-28",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA4",
    author_id: null,
    title: "Les Misérables",
    work_title: "Les Misérables",
    edition_title: null,
    authors: ["Victor Hugo"],
    isbn: null,
    format: "EPUB",
    language: "French",
    published_date: "1862-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA5",
    author_id: null,
    title: "Der Steppenwolf",
    work_title: "Der Steppenwolf",
    edition_title: null,
    authors: ["Hermann Hesse"],
    isbn: null,
    format: "PDF",
    language: "German",
    published_date: "1927-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA6",
    author_id: null,
    title: "一九八四",
    work_title: "一九八四",
    edition_title: null,
    authors: ["George Orwell"],
    isbn: null,
    format: "EPUB",
    language: "Japanese",
    published_date: "1949-06-08",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA7",
    author_id: null,
    title: "Cien años de soledad",
    work_title: "Cien años de soledad",
    edition_title: null,
    authors: ["Gabriel García Márquez"],
    isbn: null,
    format: "PDF",
    language: "Spanish",
    published_date: "1967-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA8",
    author_id: null,
    title: "The Three-Body Problem",
    work_title: "The Three-Body Problem",
    edition_title: null,
    authors: ["Liu Cixin"],
    isbn: "9780765382030",
    format: "EPUB",
    language: "English",
    published_date: "2008-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FA9",
    author_id: null,
    title: "Structure and Interpretation of Computer Programs",
    work_title: "Structure and Interpretation of Computer Programs",
    edition_title: null,
    authors: ["Harold Abelson", "Gerald Jay Sussman"],
    isbn: "9780262510875",
    format: "PDF",
    language: "English",
    published_date: "1996-07-25",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
    author_id: null,
    title: "Domain-Driven Design",
    work_title: "Domain-Driven Design",
    edition_title: null,
    authors: ["Eric Evans"],
    isbn: "9780321125217",
    format: "MOBI",
    language: "English",
    published_date: "2003-08-30",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FAB",
    author_id: null,
    title: "Le Comte de Monte-Cristo",
    work_title: "Le Comte de Monte-Cristo",
    edition_title: null,
    authors: ["Alexandre Dumas"],
    isbn: null,
    format: "EPUB",
    language: "French",
    published_date: "1844-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FAC",
    author_id: null,
    title: "Die Verwandlung",
    work_title: "Die Verwandlung",
    edition_title: null,
    authors: ["Franz Kafka"],
    isbn: null,
    format: "AZW3",
    language: "German",
    published_date: "1915-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FAD",
    author_id: null,
    title: "La sombra del viento",
    work_title: "La sombra del viento",
    edition_title: null,
    authors: ["Carlos Ruiz Zafón"],
    isbn: null,
    format: "EPUB",
    language: "Spanish",
    published_date: "2001-01-01",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FAE",
    author_id: null,
    title: "Kafka on the Shore",
    work_title: "Kafka on the Shore",
    edition_title: null,
    authors: ["Haruki Murakami"],
    isbn: "9781400079278",
    format: "EPUB",
    language: "Japanese",
    published_date: "2002-09-12",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
  {
    kind: "work",
    edition_id: null,
    work_id: "01ARZ3NDEKTSV4RRFFQ69G5FAF",
    author_id: null,
    title: "Refactoring",
    work_title: "Refactoring",
    edition_title: null,
    authors: ["Martin Fowler"],
    isbn: "9780134757599",
    format: "MOBI",
    language: "English",
    published_date: "2018-11-20",
    score: 0,
    explanation: null,
    snippet_text: null,
    snippet_highlighted: [],
    grouped_edition_ids: [],
    source: "catalog",
  },
];
